FROM alpine:latest

RUN apk add --no-cache \
    build-base \
    cmake \
    openssl-dev \
    zlib-dev \
    ncurses-dev \
    wget \
    libstdc++ \
    linux-headers \
    openssh tcpdump

WORKDIR /usr/src

RUN wget https://github.com/baresip/re/archive/refs/tags/v3.23.0.tar.gz -O re-3.23.0.tar.gz && \
    wget https://github.com/baresip/baresip/archive/refs/tags/v3.23.0.tar.gz -O baresip-3.23.0.tar.gz && \
    tar xzf re-3.23.0.tar.gz && \
    tar xzf baresip-3.23.0.tar.gz

WORKDIR /usr/src/re-3.23.0
RUN cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build -j && \
    cmake --install build

WORKDIR /usr/src/baresip-3.23.0
RUN cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DMODULES="account;menu;stdio;cons;debug_cmd;netroam;g711" && \
    cmake --build build -j && \
    cmake --install build

